- README.md
Make the following changes:
-Add installer for the 'cat' command line tool
-Update location of mbed-driver library
-Update mbedhtrun command to reflect new name of test-hello.bin
-Add instructions on how to create test.txt
> Fix problems found from OOB testing

- mbed_greentea/mbed_greentea_dlm.py
Added simple functions to lock platforms for multiple Greentea instances shared by one OS user.
This functionality is used to support ```--lock``` switch mechanism (not yet implemented fully).
> Add missing functions from locking mechanism functionality

- mbed_greentea/mbed_greentea_cli.py
- test/mbed_gt_test_parallel.py
Added new experimental feature: thread model for running mulitple test jobs in parallel on multiple resources instances (boards) of the same type within greentea, where for each board we have a separate thread.
Currently each unique MUT (mbed under test) is flashed separately one by one, but with this new feature we are able to flash multiple boards at the same time, run test case on hardware and get results in parallel.
Test execution time is reduced by n where n is number of MUTs (MUT: mbed under test).
At the moment the parallelisation is only for resource instances of the **same type**.
Don't use the ```--verbose-test-result``` mode with the new ```--parallel``` mode.
To test in parallel use:
```
$ mbedgt -t frdm-k64f-gcc --parallel 2
```
Where ```-t``` specifies the target and …
> Experimental, parallel test execution

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_yotta_target_parse.py
- test/mbed_gt_test_parallel.py
- test/mbed_gt_yotta_config.py
* Add yotta_config.json parsing support.
* ```yotta_config::mbed-os::stdio::default-baud``` setting read.
* Change dafault yotta connfiguration baudrate (```default-baud```) to ```115200```.
Example yotta configuration with baudrate
```json
{
"minar": {
"initial_event_pool_size": 50,
"additional_event_pools_size": 100
},
"mbed-os": {
"net": {
"stacks": {
"lwip": true
}
},
"stdio": {
"default-baud": 9600
}
},
}
```
This feature is using extended port configuration in ```mbed-host-tests```
* https://github.com/ARMmbed/htrun/pull/34 and exact related commit
* https://github.com/ARMmbed/htrun/commit/a0d5297489b442c389072b04c60dfdac435eacb7
```mbedhtrun``` will be called with a baudrate added to serial port command line switch, here ```-p COM172:9600```:
```
mbedhtrun -d G: -p COM172:9600 -f …
```
> Add yotta config parse

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_target_info.py
- test/mbed_gt_target_info.py
- test/mbed_gt_test_parallel.py
Currently we are suing ```yotta search``` command to check for compatible with connected device yotta targets.
New functionality uses locally stored yotta targets (```mymodule/yotta_targets``` directory) to do so and allows user to add yotta registry results with new command line switch ```--yotta-registry```.
This method is much faster than yotta registry queries and allows users to work and test off-line !
```
$ mbedgt -V --config
```
```
mbedgt: checking for yotta target in current directory
reason: no --target switch set
mbedgt: checking yotta target in current directory
calling yotta: yotta --plain target
mbedgt: assuming default target as 'frdm-k64f-gcc'
mbedgt: detecting connected mbed-enabled devices...
mbedgt: detected 2 devices
detected 'K64F' -> 'K64F[0]', console at 'COM176', …
```
> Add local yotta targets scan for mbed-target keywords

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_greentea_log.py
Fix for issue https://github.com/ARMmbed/greentea/issues/45.
Now dependency module ```xxxxxx``` import fails user will receive message like this:
```
mbedgt: Not all required Python modules were imported!
mbedgt: No module named xxxxxx
mbedgt: Check if:
1. You've correctly installed dependency module using setup tools or pip:
* python setup.py install
* pip install <module-name>
2. There are no errors preventing import in dependency modules
See: https://github.com/ARMmbed/greentea#installing-greentea
```
> [Bugfix] greentea ignores import errors

- mbed_greentea/mbed_target_info.py
With this Greentea can run tests on the [nRF51822-mKIT](https://www.mbed.com/en/development/hardware/boards/nordic/nrf51822/) board. Without this entry Greentea tries to load the .bin file, which do not work on the nRF51822-mKIT board.
> Add target info for NRF51822

- README.md
- docs/QUICKSTART.md
Changes for:
* https://github.com/ARMmbed/greentea/pull/33 (Dynamic host test loader (from directory location) - support)
* https://github.com/ARMmbed/greentea/pull/41 (Add yotta config parse)
* https://github.com/ARMmbed/greentea/pull/42 (Add local yotta targets scan for mbed-target keywords)
> README updates for few last pull requests (features)

- docs/QUICKSTART.md
- mbed_greentea/mbed_greentea_cli.py
- test/mbed_gt_test_filtered_test_list.py
- test/mbed_gt_test_parallel.py
Added new switch ```--skip-test``` respectively ```-i``` to ignore test cases.
Fixes issue #36 
If you use ```--skip-test``` option with ```--test-by-names``` option, only test_by_names will be applied.
Use the option ```-i <test-name>``` to skip a specific test (using name matching). You can use a comma to skip more than one test case. ```<test-name>``` is the name of the test case's binary (without an extension).
```
$ mbedgt --list
mbedgt: available tests for built targets, location 'C:\Users\stefan.gutmann@arm.com\Documents\GitHub\mbed-drivers\build'
target 'frdm-k64f-gcc':
test 'mbed-drivers-test-serial_interrupt'
test 'mbed-drivers-test-blinky'
test 'mbed-drivers-test-div'
test 'mbed-drivers-test-cstring'
test 'mbed-drivers-test-stdio'
test 'mbed-drivers-test-stl'
test …
```
> Switch to ignore test cases

- mbed_greentea/mbed_test_api.py
- test/mbed_gt_test_parallel.py
Fix for issue #48 
For notifying abort event to mbedhtrun stdin pipe is opened while soawning. 
stdin is closed when mbedhtrun is required to be aborted. 
greentea waits for 5 seconds to mbedhtrun to cleanup and exit. If not it terminates mbedhtrun.
mbedhtrun is also updated in PR https://github.com/ARMmbed/htrun/pull/54 to read stdin and exit gracefully when stdin is closed.
> Notify abort event to mbed-htrun via stdin pipe

- mbed_greentea/cmake_handlers.py
- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- test/mbed_gt_test_parallel.py
* Adds test case execution order shuffle:
* ```-u```, ```--shuffle``` flag used to randomly shuffle test execution.
* ```--shuffle-seed <float>``` - flag used to pass custom shuffle seed. Note: ```<float>```: should be in ```[0, 1)```.
* Greentea prints current shuffle seed in log:
```
mbedgt: shuffle seed: 0.1806805564
```
Value ```0.1806805564``` can be used with ```--shuffle-seed``` to order test case execution the same way in future run.
Note: If you shuffle different number of tests even seed is the same test order will be different. So please shuffle with seed the same list of tests!
* Implements https://github.com/ARMmbed/greentea/issues/68.
* Text test report summary sorted by target name and test name.
* List from ```--list``` sorted by test name.
* Execute all yotta module tests …
> Shuffle test execution order

- mbed_greentea/mbed_test_api.py
Fix for issue #70 
Currently greentea terminates a test when {{end}} is read on stdout of mbedhtrun. Even if it is part of an error message. Like: HOST: Unknown test property print format: {{end}}
Originally issue was reported on mbedhtrun ARMmbed/htrun#44. Please this issue for steps to reproduce.
> greentea should only end a test when ^{{end}}$ is received. Issue 70

- README.md
Changes:
* Added [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/) usage examples to README.md to point people to info how to use our tools with isolated environments.
> Add virtualenv usage description to README.md

- mbed_greentea/mbed_target_info.py
I found that tests were failing because greentea wasnt using the -combined.hex file with merged softdevice.
https://github.com/ARMmbed/mbed-drivers/issues/143
My seeed firmware reports target arch_ble which is an nrf51822 variant which is hardcoded here. 
It might be better to encode this information into the target instead?
> add arch_ble target from seeed

- mbed_greentea/mbed_coverage_api.py
- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
If mbed target is compiled with ```-fprofile-dir=.``` it will print .gcda file paths relative to ```./build/<yotta target>```. Changes here are to save these files with a prefix ```./build/<yotta target>```.
> Saving gcov .gcda files with relative path.

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_yotta_module_parse.py
- test/mbed_gt_yotta_module.py
Added detection of greentea-client dependency. Print warning if greentea-client is not in dependencies and abort test.
Fixes issue #84 
Example shows console output if greentea-client is not specified.
```
$ mbedgt -VS
mbedgt:
*****************************************************************************************
* We've noticed that NO 'greentea-client' module is specified in                        *
* dependency/testDependency section of this module's 'module.json' file.                *
*                                                                                       *
* This version of Greentea requires 'greentea-client' module.                           *
* Please downgrade to Greentea before v0.2.0:                                           *
* …
```
> Add greentea-client dependency detection

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_yotta_module_parse.py
- test/mbed_gt_yotta_config.py
- test/mbed_gt_yotta_module.py
Added detection of greentea-client dependency. Print warning if greentea-client is in dependencies and abort test.
Fixes issue #84 
Example shows console output if greentea-client is not specified.
```
$ mbedgt 
mbedgt:
*****************************************************************************************
* We've noticed that 'greentea-client' module is specified in dependency/testDependency *
* section of this module's 'module.json' file.                                          *
*                                                                                       *
* This version of Greentea doesn't support 'greentea-client' module.                    *
* Please uprade to Greentea after v0.2.0:                                               *
* …
```
> [master_v0_1_x] Add greentea-client dependency detection

- mbed_greentea/mbed_report_api.py
This PR fixes #87.
When storing Junit result we encode certain characters so they can be dumped to Junit XML report.
Currently we will just ignore all non-ascii characters, it the future we might add additional non-ascii / user friendly binary data dump.
```python
Traceback (most recent call last):
File "C:\jslv3_2\ws\gtt\venv\Scripts\mbedgt-script.py", line 9, in <module>
load_entry_point('mbed-greentea', 'console_scripts', 'mbedgt')()
File "c:\jslv3_2\ws\gtt\venv\src\mbed-greentea\mbed_greentea\mbed_greentea_cli.py", line 315, in main
cli_ret = main_cli(opts, args)
File "c:\jslv3_2\ws\gtt\venv\src\mbed-greentea\mbed_greentea\mbed_greentea_cli.py", line 842, in main_cli
junit_report = exporter_testcase_junit(test_report, test_suite_properties=yotta_module.get_data())
File …
```
> Add try/catch around encoding for JUNIT stdout/stderr

- mbed_greentea/mbed_greentea_hooks.py
- test/mbed_gt_hooks.py
Because some test cases for now may not return any LCOV output, an empty test_case_name.info file is generated. This can not be merged to result.info and the automation fails. This PR fixes the issue by enabling a feature to check for empty files or if file exists.
To enable code coverage use:
```
mbedgt -VS --hooks=lcov
```
By using a hook named ```lcov``` code coverage output is enabled and the files are autoamtically checked if they exists or empty.
> Add lcov hook

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_yotta_api.py
Recent changes:
* https://github.com/ARMmbed/greentea/releases/tag/v0.2.10 ->
* https://github.com/ARMmbed/greentea/pull/113 -> 
* https://github.com/ARMmbed/greentea/pull/113/files#diff-dede25ea3355a799ef1ec00a411ffd73L942
influenced reporters, especially JUnit reporter which is expecting test_suite_properties passed to it.
Problem:
* When calling ```mbedgt``` with ```--report-junit``` we have a traceback because JUNIT reporter function receives ```None``` as a optional parameter value.
* I've added simple guard around it in second commit, but first commit actually adds yotta module info to reporter so reporter can produce better reports with yotta module name etc.
* In the future we can add support for New Configuration JSON file and pass it to reporter to achieve the same verbosity. …
> Issue with JUNIT reporter, switch --report-junit affected

- mbed_greentea/mbed_report_api.py
This PR adds a test case's error message to the junit report. Previously this was always blank.
```
<error type="error">...</error>
```
```
<error message="ERROR" type="error">...</error>
```
@mazimkhan @PrzemekWirkus
> Adding test case result text to test report

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
- mbed_greentea/mbed_yotta_api.py
- mbed_greentea/mbed_yotta_module_parse.py
- mbed_greentea/tests_spec.py
- test/mbed_gt_tests_spec.py
Changes:
* Add filter by name for `TestSpec.get_test_builds()`
* Polishing: Remove debug prints from [tests_spec](https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/tests_spec.py)
* Bug-fix for #119
* Add correct prints to warnings (switch `-n`)
* `YottaModule` functionality polishing
* Add to `Junit.TestSuite.properties` values of `toolchain` and `target` so Viewer can take produce reporting.
```xml
<?xml version="1.0" ?>
<testsuites errors="0" failures="0" skipped="0" tests="4" time="0.300000190735">
<testsuite errors="0" failures="0" name="unknown.frdm-k64f-gcc" skipped="0" tests="4" time="0.300000190735">
<properties>
<property name="toolchain" value="GCC_ARM"/>
<property name="target" value="K64F"/>
</properties>
```
* Error should be reported only if module.json exists …
> Patches on top of Greentea v0.2.11 (bug-fixes and allignment with test specification feature)

- mbed_greentea/mbed_greentea_cli.py
Change:
* Serial port baudrate is doubled for multiple builds from test spec, see #123 
* This issue appears only when we are using multiple test sepc configurations or specify multiple yotta targets with -t switch
Correct baudrate for second pass for `mbedgt: processing target 'K64F' toolchain 'GCC_ARM' compatible platforms...` build:
```
mbedgt --test-spec ts.json --config -v
mbedgt: detecting connected mbed-enabled devices...
mbedgt: detected 2 devices
detected 'K64F' -> 'K64F[0]', console at 'COM218', mounted at 'E:', target id '0240000033514e450043500585d4003fe981000097969900'
detected 'K64F' -> 'K64F[1]', console at 'COM220', mounted at 'G:', target id '0240000033514e45002e500585d4001ee981000097969900'
mbedgt: processing target 'K64F' toolchain 'ARM' compatible platforms...
mbedgt: …
```
> Bug-fix for #123: do not add baudrate multiple times to serial port definitions

- README.md
- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
- mbed_greentea/tests_spec.py
Currently after we've added `--test-spec` switch users have to explicitly declare it after building with <build system> which outputs test spec. So:
* I've updated [README.md](https://github.com/ARMmbed/greentea/tree/devel_test_spec_pickup#test-specification-json-formatted-input) with some test specification info.
* if `test_spec.json` (which is default name of test spec returned by <build system>) exist in directory in which we are calling Greentea (`mbedgt` command) we will pick it up as default test spec. This action will be equal to calling Greentea with explicit `--test-spec test_spec.json` switch.
* If `module.json` exist in directory we will assume this is a yotta module and act accordingly.
* If both `module.json` and `test_spec.json` exist we will give priority to …
> Add test_spec.json as default name for test spec

- mbed_greentea/mbed_common_api.py
- mbed_greentea/mbed_target_info.py
- test/mbed_gt_target_info.py
When yotta is not installed we still should be able to check currently set 
* Add parsing function for `'yotta.json`.
* Add proper unit tests.
* Fixed not handled `OSError` in `run_cli_process` function.
Use case is like this: On a host without yotta installed, for example think CI slave we still would like to fetch `yotta target` information passed there with the build. This information is originally checked with `$ yotta --plain target` command. We would like to avoid command line execution and parse `.yotta.json` file in root of yotta module.
This will even stronger decouple Greentea from build system which now is optional.
Note: This is a part of an effort to completely decouple build system from Greentea so we can use test specification instead.
```
mbedgt: using 'module.json' from …
```
> Greentea should check for yotta target first from local .yotta.json file

- mbed_greentea/mbed_target_info.py
This is a response for #131
Changes:
* Add default behavior to 'get_platform_property'.
* Add `default` node to `TARGET_INFO_MAPPING` with default values across all platforms. Used when we call `get_platform_property`.
> Add default behavior to 'get_platform_property'

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
This is a response for #134 
Changes:
* New `int` result handler for calles to `run_host_test`
* `run_host_test` function can now return integer values if there is an issue.
* Better exception handler for `run_host_test.run_command()` function.
* `run_host_test.run_command()` will return None if process can't be executed.
* Minor refactoring.
Now if command fails we will see:
```
mbedgt: mbed-host-test-runner: started
mbedgt: run_host_test.run_command(['mbedhtrun', '-d', 'E:', '-p', u'COM218:9600', '-f', u'".\\build\\frdm-k64f-gcc\\test\\mbed-drivers-test-generic_tests.bin"', '-C', '4', '-c', 'shell', '-m', 'K64F', '-t', '0240000033514e450043500585d4003fe981000097969900', '-e', '"./test/host_tests"']) failed!
[Error 2] The system cannot find the file specified
```
> #134: TypeError caused by incorrect formatting of error message in run_host_test function

- mbed_greentea/cmake_handlers.py
* While porting I notices that having sorted list of tests helps :P
```
$ mbedgt -l
mbedgt: using 'test_spec.json' from current directory!
mbedgt: available tests for built 'K64F-GCC_ARM', location '.\.build/tests\K64F\GCC_ARM'
test 'ccc'
test 'aaa'
test 'bbb'
```
```
$ mbedgt -l
mbedgt: using 'test_spec.json' from current directory!
mbedgt: available tests for built 'K64F-GCC_ARM', location '.\.build/tests\K64F\GCC_ARM'
test 'aaa'
test 'bbb'
test 'ccc'
```
> Adds lexicographic order to switch --list for test specification

- mbed_greentea/mbed_greentea_cli.py
When using Greentea switch `-n` and putting `*` at the end of test suite name filter will run to filter in all test suite names starting with string before `*`.
1) Filter all tests with names starting with 'mbed-drivers-t', e.g.:
* tests-mbed_drivers-ticker
* tests-mbed_drivers-ticker_2
* tests-mbed_drivers-ticker_3
* tests-mbed_drivers-timeout
```
$ mbedgt -VS -n mbed-drivers-t*
```
2) Filter all tests with names starting with 'mbed-drivers-t' and test case
'tests-mbed_drivers-rtc', e.g:
* tests-mbed_drivers-rtc
* tests-mbed_drivers-ticker
* tests-mbed_drivers-ticker_2
* tests-mbed_drivers-ticker_3
* tests-mbed_drivers-timeout
```
$ mbedgt -VS -n mbed-drivers-t*,tests-mbed_drivers-rtc
```
```
mbedgt: test suite report:
+--------------+---------------+-----------------------------+-------- …
```
> Add simple 'test-name-prefix*' filter to filter test cases with common prefix name

- mbed_greentea/mbed_test_api.py
Test specficatoin in the near future may bring `host_tests` directory fields. For now we can add a simple feature which will assume specific locations of the host tests directory depending on where test bianary is located
This PR introduces simple search above 'n' levels of the  path or the binary.
Assumptions:
* Path to binary starts from "build" directory, and goes 4 levels deep: `./build/tests/compiler/toolchain`.
* Binary is inside test group. For example: `<app>/tests/test_group_name/test_dir/*,cpp`.
* We will search for directory called `host_tests` on the level of test group (level=2) or on the level of `tests` directory (level=3).
If `host_tests` directory is found above test code will will pass it to `mbedhtrun` using switch `-e <path_to_host_tests_dir>` .
> Add function to search for host_tests directory on top of image path

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
- mbed_greentea/mbed_yotta_api.py
This PR addresses a few issues that arise when multiple test builds are present in a test spec.
- Properly sets test build properties in the JUnit XML report. Fixes issue #138.
- Fixes issue where only one test build isexecuted even if no test build filter is applied.
- Removes yotta module name prefix from the test report
- If this needs to be added back, then I'd propose adding the yotta module name to the "test build name", so it would look like `<yotta module name>.<yotta target name>`
@PrzemekWirkus please review
@mazimkhan, @adbridge, FYI
> Fixing issues when multiple test builds exist

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_target_info.py
- mbed_greentea/mbed_test_api.py
Changes:
* Add support for mbed-os/mbed/hal/targets.json
* Now users can additionally use flag `-R` (timeout in seconds after reset) with `mbedhtrun`.
* Just define in `targets.json` additional field `forced_reset_timeout`.
* Example: Define delay after reset to 3.2 seconds inside `targets.json` file:
```json
"K64F": {
"forced_reset_timeout": 3.2,
"supported_form_factors": ["ARDUINO"],
"core": "Cortex-M4F",
"supported_toolchains": ["ARM", "GCC_ARM", "IAR"],
},
```
> Add support for mbed-os/mbed/hal/targets.json

- mbed_greentea/mbed_greentea_cli.py
- test/mbed_gt_test_filtered_test_list.py
Changes:
* Now you can specify `-n <name>*` and `-i <names>` together
* Added unit tests for this command mix
```
$ mbedgt -VS -n mbed-drivers-test-t* -i mbed-drivers-test-ticker_3
```
```
...
mbedgt: test case filter (specified with -n option)
test filtered in 'mbed-drivers-test-ticker'
test filtered in 'mbed-drivers-test-ticker_2'
test filtered in 'mbed-drivers-test-ticker_3'
test filtered in 'mbed-drivers-test-timeout'
mbedgt: test case filter (specified with -i option)
test filtered out 'mbed-drivers-test-ticker_3'
...
```
> Add support for ignoring tests (using -i switch) specified with -n <names>* notation.

- test/mbed_gt_test_filtered_test_list.py
Changes:
* Add unit tests for cases like `-n xxxx*,yyyy*`
* Add unit tests for cases like `-n xxxx*,yyyy* -i zzzz,yyyy-aa`
> Add more unit tests for cases of -n with multpile '*' entries

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
Changes:
* Replace verbose prints for available devices and devices under tests with simple tables (like mbed-ls).
* It makes Greentea log shorter and easier to read.
```
mbedgt: detecting connected mbed-enabled devices...
mbedgt: detected 4 devices
+---------------+----------------------+-------------+-------------+--------------------------------------------------+
| platform_name | platform_name_unique | serial_port | mount_point | target_id                                        |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+
| NUCLEO_F401RE | NUCLEO_F401RE[0]     | COM163      | E:          | 07200200076165023804F31F                         |
| K64F          | K64F[0]              | COM219      | F:          | …
```
> Replace available devices and MUTs in use for test prints with pretty table

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
- test/mbed_gt_test_api.py
* Add support for new `utest` events `__testcase_count` and `__testcase_name`.
* Add support in code for `SKIPPED` test case result in test results.
* Now if `utest` will provide information about test case names (see events above) we can use this to update list of all test cases missing from log with status `SKIPPED`. See below:
* JUNIT report will be now decorated with SKIPPED test cases so we can actually check how many were dropped during testing. This will allow us to generate reports with test cases count for: tests passed, failed and skipped (so we can get total too!) :) No test case left behind!
JUnit node `<system-out>` will have full `htrun` log, `<system-err>` will hold full `utest` log for particilar test case. For SKIPPED test cases
* mbed-os: [ Provide list of test case …
> Add support for SKIPPED test cases

- mbed_greentea/mbed_greentea_cli.py
@mlnx This PR addresses issue *[minor] Reported passes vs failures miscount info*. see #157.
```
mbedgt: test case summary mismatch: reported passes vs failures miscount!
(47, 0) vs (41, 0)
```
```
mbedgt: utest test case summary mismatch: utest reported passes and failures miscount!
reported by utest: passes = 47, failures 0
test case result count: passes = 41, failures 0
```
> Add information about origin of passes / failures in miscount warning

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
When using `mbedgt -l` without `test_spec.json` in current directory we were unable to list test cases with standard list command line switch. With this improvement we can list test specification content on screen. 
This PR changes the way Greentea looks for yotta module, test specification file. Order is:
* Test specification defined with `--test-spec`
* Local directory `test_spec.json`
* Recursive search and merge of test specifications from `./.build` directory
* Recursive search and merge of test specifications from `./mbed-os/.build` directory
* Local directory `module.json`
```
[master] C:\Work\mbed-os> mbedgt -l
```
```
mbedgt: greentea should be run inside a Yotta module or --test-spec switch should be used.
mbedgt: exited with code -1
```
```
[master] C:\Work\mbed-drivers> mbedgt …
```
> Add recursive search for test_spec.json in mbed-os and mbed-os app dir level

- mbed_greentea/mbed_greentea_cli.py
- test/mbed_gt_cli.py
Changes:
* Add version print at the beggining of `mbedgt` command execution:
```
$ mbedgt -l
mbedgt: greentea test automation tool ver. 1.0.1
```
> Add API to fetch mbed-greentea package version string

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
* Add `mbed-ls` dummy platform used for triggering workflow for glbal resource manager
* See https://github.com/ARMmbed/mbed-ls/pull/107
* Add command line switch `--grm` which will be passed to `htrun` for global resource allocation
* Example: `--grm K64F:raas_client:10.2.302.41:8000`
* Supporting for https://github.com/ARMmbed/htrun/pull/108
Calling global resource manager from Greentea command line requires:
* Greentea must be called from the same directory yuou would call any non-remote (local) tests
* Greentea must find tests in range, please use `$ mbedgt --list` to verify you can access tests
* You must provide explicitly Greentea command line switches: `--grm`
* You can mix it with for example: `-V`, `-t`, `-n`, `---report-junit`
* You must explicitly specify with switch `--grm`: …
> Add support for command line switch --grm between greentea and htrun

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_greentea_log.py
- mbed_greentea/mbed_test_api.py
* Response for #167 (suppress logs in non-verbose `-V` switch mode)
* Changed few logs to be suppressed when executing Greentea without `-V` flag.
* Add `print_text` to logger `gt_log_tab()` function. Now we can steer logging e.g. without awkward:
```python
if verbose:
logger.gt_log_tab("TEXT")
```
but with more convenient:
```python
logger.gt_log_tab("TEXT", print_text=verbose)
```
```
$ mbedgt -n tests-mbed_drivers-generic_tests
```
```
mbedgt: greentea test automation tool ver. 1.1.1
mbedgt: using multiple test specifications from current directory!
using '.build\tests\K64F\GCC_ARM\test_spec.json'
mbedgt: detecting connected mbed-enabled devices...
mbedgt: detected 1 device
mbedgt: processing target 'K64F' toolchain 'GCC_ARM' compatible platforms... (note: switch set to --parallel 1) …
```
> Response for #167 (suppress logs in non -V mode

- mbed_greentea/mbed_greentea_cli.py
* Fixes #164 - fingers crossed! :P
* Only add MUT to list of MUTs under test when MUT is not on the list.
Checked with two builds:
```
+--------------+---------------+-----------------------------+--------+--------------------+-------------+
| target       | platform_name | test suite                  | result | elapsed_time (sec) | copy_method |
+--------------+---------------+-----------------------------+--------+--------------------+-------------+
| K64F-GCC_ARM | K64F          | tests-mbed_drivers-ticker   | OK     | 23.43              | shell       |
| K64F-GCC_ARM | K64F          | tests-mbed_drivers-ticker_2 | OK     | 23.42              | shell       |
| K64F-GCC_ARM | K64F          | tests-mbed_drivers-ticker_3 | OK     | 23.52              | shell       |
| K64F-IAR     | K64F …
```
> Add uniquely MUTs to list of MUTs which will be used for testing

- mbed_greentea/mbed_report_api.py
This commit should fix an issue with the HTML report where sometimes
clicking on the OK/FAIL button does not bring up the test summary. It uses
the getElementById function in addition to the div id string to correctly
fetch the element and hide/show it.
This should help address #182.
Please review at @ConorPKeegan 
FYI @mazimkhan
> Using getElementById for fetching elements in HTML report

- mbed_greentea/mbed_report_api.py
* When splitting up <PLATFORM>-<TOOLCHAIN>, we now only take the last element of the split (the toolchain, as it should not contain a '-'), and then remove that from the original string to get the platform
* Problem occurred when platform contained a '-'
* This pull request fixes #181
> Fix for Issue 181

- mbed_greentea/mbed_greentea_cli.py
This PR addresses #187. Previously if you specified multiple targets with the `-t` option, it would not copy the binary to the correct device, for example if you ran:
```
mbedgt -V -v -t K64F-GCC_ARM,NUCLEO_F401RE-GCC_ARM
```
The first test run would copy to the K64F correctly, but when the next run was supposed to copy to the NUCLEO_F401RE, it would copy to the K64F instead.
Looks like the issue was the `muts_to_test` variable. This should change between test builds, however it was being kept in global scope. I've now moved it withing the scope of the test build loop so it should reset with each iteration.
> Multi-target runs now copy to the correct device

- mbed_greentea/mbed_report_api.py
This was first reported by @jeromecoutant, thanks!
This addresses #186. The root cause of the issue was when exporting HTML reports, it was assumed that all the same test cases would be run on all the targets. However, this is not always true. This PR adds a 'NOT_RAN` box to a test that did not run on the current target but DID run on at least one target.
Please review @ConorPKeegan
FYI @mazimkhan
> Handle case where tests aren't in each target run

- mbed_greentea/mbed_greentea_cli.py
Before, if any key was set to null by mbed-ls, greentea would immediately
error. This commit relaxes this requirement so only the following keys
need to be set: 'target_id', 'platform_name', 'serial_port', 'mount_point'.
Note this includes the commit from #177 since this affects devices that are usually mocked as well. If you would prefer that commit to be removed from this PR then I can do that.
Please review @mazimkhan @ConorPKeegan
> Tolerate missing mbed-ls info

- mbed_greentea/mbed_test_api.py
In my last PR (https://github.com/ARMmbed/greentea/pull/193), I submitted a bad patch that made a call to `os.listdir` incorrectly. This was noticed by @jeromecoutant in #194. This commit should fix that and restore `mbedgt --list` functionality.
Please review @mazimkhan
> Patching incorrect call to os.listdir (Fixes #194)

- CONTRIBUTING.md
- README.md
- mbed_greentea/cmake_handlers.py
- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
- mbed_greentea/tests_spec.py
- test/mbed_gt_tests_spec.py
* Added support for new test_spec.json format
* Will extract the test cases for each binary
* Backwards compatibility so nothing changes if the test cases are not specified
* Added support for the filtering of tests by test case
* Added support for the parsing of a Testlink test plan with command line switch `--testlink-test-plan <FILE>`
* Chooses the tests to run based on the test cases specified
* Added command line switch to output all of the test casesfound, for all of the builds `--list-test-cases`
* Added command line switch to ouput all of the test cases from the test plan, showing the implemented, not implemented, and conflicting, using `--list-test-plan`
* Added exporter to produce report for Testlink in XML format
* Added command line switch `--report-testlink-xml <FILE>` to …
> Added support for Testlink

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_target_info.py
This PR was spurned by the latest restructure of mbed OS. Greentea is no longer finding the target information correctly within mbed OS. There are two main changes that are included in this PR:
1) It allows greentea to find inherited properties from parent targets.
2) It makes greentea perform a directory walk in search of a `targets.json` file. Previously, there were only a few hardcoded locations that were searched for this file. This operation is more expensive unfortunately, however it is a far more robust solution. It no longer makes assumptions on the project's structure. It should be resilient against any more changes made to the structure of mbed OS.
The performance on my machine was ~1 second for every call to `get_platform_property_from_targets`. I moved the call to this …
> Searching project recursively for target information

- mbed_greentea/mbed_greentea_cli.py
method on a NoneType.
On windows 7 if a target was detected but for some reason the serial port
was not, then mbed-ls would return a NoneType for the serial port field in
the ready_mbed_devices list. This serial port field under normal
circumstances will contain a string and has the endswith() method called
on it. This is however illegal for a NoneType.
The fix is to read the serial port field first and test whether or not it
is the NoneType prior to calling the method. If it is the NoneType then
report an error and skip this target.
> Fixes issue #198 where an error occurs when trying to use the endswith()

- mbed_greentea/mbed_test_api.py
If a test contains invalid ASCII characters and you attempt to export to JSON or HTML, you will receive a traceback. You can reproduce this by using commit 8a9a2463563af3ffb8d289905d3f7073a46ecc80 of mbed-os and running the following commands:
```
mbed test --compile -m NCS36510 -t GCC_ARM -n tests-mbedmicro-mbed-cpp
[...]
mbed test --run -m NCS36510 -t GCC_ARM -n tests-mbedmicro-mbed-cpp --report-html report.html -v
[...]
mbedgt: exporting to HTML file 'C:/mbed_jenkins/test_node_2/workspace/tm_wrap/754/.axes/target/NCS36510/toolchain/GCC_ARM/test_report_NCS36510-GCC_ARM.html'...
mbedgt: unexpected error:
'ascii' codec can't decode byte 0xff in position 1348: ordinal not in range(128)
Traceback (most recent call last):
File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main …
```
> Scrubbing log of unprintable characters

- mbed_greentea/mbed_test_api.py
This change enables running host tests with grm
fixes https://github.com/ARMmbed/greentea/issues/206
> Passing -e option to mbedhtrun even when using grm

- mbed_greentea/mbed_report_api.py
This PR modifies the top level HTML page generated during a test specified with parameters: --report-html=output.html. The intent for the modifications is to create a cleaner report for giving to clients or executives with easy to read pass rates for each test.
Each test now contains a pass rate, along with a ratio of total tests passed to total tests.
CC: @bridadan @BlackstoneEngineering
> Added pass rates in HTML report

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
This allows greentea to pickup runtime memory metrics that greentea client can output. You can save the information in a CSV file or in the JSON report. The CSV file is useful for the [Plot plugin in Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Plot+Plugin).
The CSV file can be generated by adding the `--report-memory-metrics-csv <filename>` option.
Please review @mazimkhan
> Adding memory metrics tracking and reporting.

- mbed_greentea/mbed_greentea_cli.py
mbedgt creats a dummy device when using grm.
When the --parallel option is enabled, there
is still only one dummy device, hence parallel
test execution does not work.
This fix add multiple dummy devices according
to the number specified by the --parallel option.
Thus enable test execution in parallel.
Limitation:
mbedgt still does not know how many devices are
actually available in the grm, hence the burden
of making sure there are available devices falls
on the user.
> Enable parallel test execution with grm

- README.md
@iriark01 suggested that we add a line to Greentea's docs describing how to contribute to the project since it's not located in the mbed OS repository. Greentea's README is in the Handbook now, so this provides a link to the contributing doc. The conversation can be found here: https://github.com/ARMmbed/Handbook/pull/145.
Could you please review @AnotherButler? Also @mazimkhan and/or @adbridge.
> Add line about contributing to Greentea in the README

- mbed_greentea/mbed_greentea_cli.py
This commit allows targets to specify custom "copy" and "reset" methods
when testing with Greentea. This method should not be used extensively.
It is intended to be used by targets that don't have a typical mbed
interface.
It is needed to enable targets like the ARM MPS2: https://developer.mbed.org/platforms/ARM-MPS2/
FYI @ashok-rao @screamerbg 
Could you please take a look @adbridge @mazimkhan
> Getting copy and reset methods from mbed-os targets.json.

- mbed_greentea/mbed_test_api.py
@bridadan @mazimkhan @studavekar : Please review code
Many boards in CI fail just after sync, suggestion to which was re-flash firmware and re-try. Capturing SYNC failure as separate for such cases.
Also would like to know more about SYNC=2 value, increasing that will have impact on anything?\
Note: Code changes in htrun should be pulled along with this request
> SYNC failure case added: Dependent on HTRUN code

- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
This change adds total stack usage which is sum of max stack used by each
thread.
> Add total stack usage to memory matrix.

- mbed_greentea/mbed_test_api.py
In mbed OS versions 5.4.x and older, memory metrics were printed in a
format that always included a hyphenated thread "entry" and "argument".
In the coming 5.5 release, this doesn't appear to be the case, only
containing the "entry". This PR allows greentea to parse both cases.
@adbridge @mazimkhan This will be a necessary patch to include in the next release of greentea as this is currently broken on master (not the current release version, this only became an issue when #203 was merged).
> Fixing parsing of memory of metrics.

- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_test_api.py
Note: I have no idea what I'm doing!
But we are looking to add the reporting of the reserved memory regions (heap and stack). This seemed to do it, but feel free to be critical of our approach.
Sidenote: we're also looking to add the full memory regions (total rom/ram on a device) but this info is currently not available.
dependent on https://github.com/ARMmbed/greentea/pull/223, https://github.com/ARMmbed/mbed-os/pull/4504
commit range: https://github.com/ARMmbed/greentea/pull/228/commits/2a6a366100f06a0f29c4d0f6db5787650068107b
cc @studavekar, @bridadan
> Add reserved memory reporting

- mbed_greentea/mbed_test_api.py
Handled key value pairs stopped being printed in their raw received form
in https://github.com/ARMmbed/htrun/pull/130. This broke the testcase name detection in greentea.
This changes the regex to detect the testcase names in both old and new
versions of htrun.
This should address #231 I believe.
cc @mazimkhan
> Fixing regex that caused testcase names to be missed.

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
Due to transport overhead we may need to send more then 2 sync packets,
as of now using greentea doesn't have this option. This patch will enable us to
send --sync from greentea.
> take sync flag arguments and pass to mbedhtrun

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
In the process of integrating additional tests to the CI we realized it would be helpful to be able to tag particular devices in RaaS that had unique or additional setups for tests that required them (for example a K64F with an ESP8266 or Ethernet). 
Take the following tag as an example. 
There is a [separate htrun PR](https://github.com/ARMmbed/htrun/pull/163) up to implement this change, this PR will funnel the new argument to the htrun layer. Given that htrun change and the above tag setup, we could run tests with the following setup.
```
mbedgt -g "K64F:raas_client:austin-ci-linux-001:8000" --test-spec=BUILD/tests/K64F/GCC_ARM/test_spec.json --report-html=K64F_GCC_ARM.html -e tests/host_tests/timing_drift_auto.py -v -V -n features-feature_lwip-tests-mbedmicro-net-tcp_hello_world …
```
> Add option to request allocation based on specified tags

- .coveragerc
- mbed_greentea/cmake_handlers.py
- mbed_greentea/mbed_common_api.py
- mbed_greentea/mbed_greentea_dlm.py
- mbed_greentea/mbed_report_api.py
- mbed_greentea/mbed_target_info.py
- test/mbed_gt_cli.py
- test/mbed_gt_cmake_handlers.py
- test/mbed_gt_coverage_api.py
- test/mbed_gt_greentea_dlm.py
- test/mbed_gt_hooks.py
- test/mbed_gt_report_api.py
- test/mbed_gt_target_info.py
- test/mbed_gt_test_api.py
- test/mbed_gt_tests_spec.py
- test/mbed_gt_yotta_api.py
- test/resources/empty/test/CTestTestfile.cmake
- test/resources/not-empty/test/CTestTestfile.cmake
- test/resources/test_spec.json
Changes:
- Fix typo in cmake_handlers log output
- Fix typo in greentea_kettle_info() docstring
- Remove unused parameter from get_json_data_from_file()
- Reduce nesting in mbed_target_info to make it easier to test
> Increase unit test coverage and fix some minor issues

- mbed_greentea/mbed_report_api.py
- test/report_api.py
Resolves #240
Note to anyone reading:
**Never, EVER, emit this byte sequence** (as text)
> Handle pure evil non-unicode in report API

- mbed_greentea/mbed_greentea_cli.py
- test/mbed_gt_cli.py
- test/mbed_gt_target_info.py
This fixes #262. It also fixes testing on Windows since directory separators are silly.
> Fix test name globing

- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
introduced --retry-count arguments to specify retry count of individual test
failure. By default, there is no retry.
> Accept --retry-count argument that retries on test failure

- mbed_greentea/mbed_greentea_cli.py
Currently --skip-test fails to filter `test-name-*`, with this change we should be able to filter out using '*'
> allow skipping of tests using * expansion

- mbed_greentea/mbed_test_api.py
This means the message will be displayed with red highlight regardless of verbose setting.
Closes #166 #191
> Detect assert failures in htrun messages and log as error

- README.md
- mbed_greentea/mbed_greentea_cli.py
- mbed_greentea/mbed_test_api.py
In order to support FastModels in mbed testing framework, an extra option "--fm" been added to greentea.
This option will allow greentea hooks up with fm_agent module, and run tests over FastModels
The command line format of the --fm is following the RaaS_Client "--grm" convention
* "--fm" been added to mbedgt
* user could use __mbedgt  --fm \<model_name>:<config_name>__
* e.g.  __mbedgt  --srm FVP_MSP2_M3:DEFAULT__
This PR is related with other PRs regarding to FastModel support in testing framework 
ARMmbed/mbed-ls#345
ARMmbed/htrun#187
CC. @theotherjimmy @studavekar @bridadan dan @bulislaw
> add "--fm" option to support FastModels testing in greentea

- mbed_greentea/mbed_test_api.py
This is cleaning up a slight implementation detail from #289. I missed this line when making the change. This means all checks in greentea are now using the decoded output.
> Checking decoded output for test errors

- mbed_greentea/mbed_test_api.py
- test/mbed_gt_test_api.py
This should fix #294. Certain characters (typically triggered by corrupted data coming over a device's serial line) can cause greentea to crash when printing them to the console. This seems to only be an issue with Python 2.7. Handling this case universally between Python 2.7 and 3.x turns out to be quite challenging and I didn't really find any solutions I was completely happy with. This was the best compromise I could find.
Python 2.7 is perfectly happy to accept "byte-like" strings when writing to stdout. This also fixes the traceback described in #294. Python 3.x however requires "string-like" strings, so that is what the `try/except` block is doing. I also realize my terminology is off, but I looked at it for quite sometime and I still don't completely understand it. The good news …
> Fix encode failure

- src/htrun/README.md
- Updated the htrun readme based on standalone greentea
> Update the htrun readme

- .github/workflows/publish-to-pypi.yml
For any new published release of Greentea, we should automatically build
and upload the greentea-host Python distribution to PyPI. This gives us
a "tag-to-release" model, where pushing a tag will result in the PyPI
release going out.
> ci: Publish tags to PyPI

- README.md
- src/htrun/host_tests_plugins/__init__.py
- src/htrun/host_tests_plugins/module_copy_stprogrammer.py
Hi
HTRUN has a plugin to use ST-LINK utility (`stlink`)
This tool is deprecated and replaced by STM32CubeProgrammer 
https://www.st.com/en/development-tools/stm32cubeprog.html
This pull request is adding first support of this new ST tool.
Tested OK with this command:
`htrun -f xxx.bin -d F: -p COM45:115200 -c stprog --sync=0 -P 30`
> HTRUN : add STM32CubeProgrammer support
