ARMmbed/greentea

mbed_greentea/cmake_handlers.py, mbed_greentea/mbed_greentea_cli.py, mbed_greentea/mbed_greentea_dlm.py, mbed_greentea/mbed_greentea_log.py, mbed_greentea/mbed_target_info.py, mbed_greentea/mbed_test_api.py, mbed_greentea/mbed_yotta_api.py, test/mbed_gt_test_parallel.py
We are using ```--parallel <n>```  switch now and we need to at least to sync main mbedgt logs.
This PR introdyuces super simple class which is logging to stdout using mutext to control console access.
To disable colors while logging use new ```--plain``` switch.
=> Logger mutex

mbed_greentea/cmake_handlers.py, mbed_greentea/mbed_greentea_cli.py
Fix for minor issues https://github.com/ARMmbed/greentea/issues/51 & https://github.com/ARMmbed/greentea/issues/49 related to ```--list``` prints.
=> [bugfix] List - if no test available, the output is nto clear

mbed_greentea/cmake_handlers.py
This is a fix for https://github.com/ARMmbed/greentea/issues/56.
=> Check for build dir existence before trying to list tests.

docs/CONTRIBUTING.md
Changes:
* Added to CONTRIBUTING.md content related to basic coding rules and styles used in this project. 
* Basically we point people to Pythonic official documentation.
=> Add coding styles and rules notes

mbed_greentea/mbed_greentea_cli.py
Changes:
* There was a small typo related to print where instead of mentioning ```-i``` we've mentioned ```--skip-build```. Shame on us, it should be spotted during code review.
=> Polishing of #36 fix

mbed_greentea/mbed_greentea_cli.py
Add fix for issue https://github.com/ARMmbed/htrun/issues/51
=> [Bugfix] Add more verboseness when telling user about missing mbed properties

mbed_greentea/mbed_greentea_cli.py
related issue: http://jira.arm.com/browse/IOTSFW-2144
=> Fix hanging execution of greentea/htrun

README.md
pip package name for greentea has changed to mbed-greentea
=> Change greentea package name in instructions

mbed_greentea/mbed_greentea_cli.py, mbed_greentea/mbed_test_api.py
fix issue #100
related PR: https://github.com/ARMmbed/htrun/pull/73
=> Process ctrl+c from htrun

README.md, docs/PORTING.md
Note that this is a **work in progress*.
Changes;
* Add new `docs/PORTING.ms` document.
=> Add HOW TO preapre tools for new mbed platform porting

mbed_greentea/mbed_greentea_cli.py, mbed_greentea/mbed_test_api.py
Changes:
* This PR addresses #149 (improve messaging when not all properties of DUT are detected with mbed-ls).
* Small improvements / polishing.
=> Improve messaging when not all properties of DUT are detected with mbed-ls

mbed_greentea/mbed_greentea_cli.py
Changes:
* Switch `--report-json <filename>` now dumps to text file instead of stdout.
* Because other logs are captured on stdout we can't extract JSON anyway.
* It will be used in the future to capture, push to `mbed.com` result database (of course not in the same format).
* Small code refactoring.
```
$ mbedgt -VS --report-json __a.json --report-junit __a.xml --report-text __a.txt --parallel 4
```
```
...
mbedgt: exporting to JUNIT file '__a.xml'...
mbedgt: exporting to TEXT '__a.txt'...
mbedgt: exporting to JSON '__a.json'...
...
```
[__a.txt](https://github.com/ARMmbed/greentea/files/329967/__a.json.txt)
=> Fixed JSON formatted report - it should be stored to disk, not on screen (no way to catch output)

mbed_greentea/mbed_greentea_cli.py, mbed_greentea/mbed_report_api.py
* Added `--report-html <filename>` switch to trigger HTML report generation
* Added the functions needed to generate HTML reports
```
$ mbedgt -V --report-html report.html
```
* Implemented enhancement #165 
* [report.html](https://rawgit.com/ConorPKeegan/cea0f0beee3934a9529c6d268e04e21f/raw/07c1d143f097a0607c1d2589fb99e7c260298265/report.html)
=> Added HTML report generation

mbed_greentea/mbed_report_api.py
Changes:
* Add `<!DOCTYPE html>` to HTML report
* Add colors to few more HTML report issues
=> Add few color tweaks

mbed_greentea/mbed_test_api.py
With release 0.9.7 of mbed CLI, the default build directory changed from '.build' to 'BUILD'. This extends the list of checked directories to include both (prioritizing 'BUILD' over '.build'). This will backwards
compatible with older releases of mbed CLI.
Please review @mazimkhan
=> Adding 'BUILD' to list of checked directories for host test

mbed_greentea/mbed_greentea_cli.py, mbed_greentea/mbed_test_api.py, setup.py
=> merging master

mbed_greentea/mbed_greentea_cli.py
This should fix issue #150. Tested working on Windows 10 and Ubuntu Linux 16.04.
The underlying issue was that a blocking call to `join` for the worker threads was stopping `KeyboardInterrupt` exceptions from being raised to the exception handler here: https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/mbed_greentea_cli.py#L396
This fix changes the blocking call to `join` to one that timesout after 0.1 seconds. The join is called in a loop until the thread's `isAlive()` function returns False.
@geky @theotherjimmy @jupe I'm sure you'll be very happy to see this fix finally happen 😄 
@mazimkhan Could you please take a look?
=> Fixing keyboard interrupts on posix OSes

mbed_greentea/mbed_report_api.py, test/report_api.py
Resolves #236
Is breaking someone's setup. I'll make a release after this is merged
=> Correct division by zero in report code

mbed_greentea/mbed_report_api.py, mbed_greentea/mbed_target_info.py
- Remove double indention
- Use get method with default value
=> Fix remaining issues outlined in test coverage PR

mbed_greentea/mbed_target_info.py, setup.py, test/mbed_gt_target_info.py
And refactor into a bunch more tests.
Fixes #249
Closes #248
=> Correct target property priority

mbed_greentea/mbed_test_api.py
Fix for issue : https://github.com/ARMmbed/greentea/issues/260 
pass additional parameter which would be useful for htrun.
=> Pass -g, -r, -m to htrun

setup.py
* Fix test name globing
* Updates deprecated mbedls API call
* Handle uart corruption in report generation
* Pass -g, -r, -m to htrun
* Accept --retry-count argument that retries on test failure
=> Release Version 1.3.3

mbed_greentea/mbed_test_api.py, setup.py
Small fixes to allow greentea to run with Python 3.
=> Fixes string issues with running in Py3

mbed_greentea/mbed_report_api.py, mbed_greentea/mbed_test_api.py, test/mbed_gt_report_api.py
This is following discussion in https://github.com/ARMmbed/greentea/issues/277
=> Use PrettyTable with GitHub policy

mbed_greentea/mbed_target_info.py
RAPIDIOT_K64F devices take a longer time to boot up.
=> set forced_reset_timeout 10 sec for RAPIDIOT_K64F

mbed_greentea/mbed_test_api.py, test/mbed_gt_coverage_api.py
This should stop the exception occurring in #288.
=> Ignoring bad unicode characters

setup.py
This should fix the issue mentioned here: https://github.com/ARMmbed/mbed-cli/issues/782#issuecomment-438588772
=> Allow colorama versions 0.4.x

setup.py
* Add "--fm" option to support FastModels testing
* Output tables in GitHub flavored Markdown
* Set forced_reset_timeout to 10 sec for RAPIDIOT_K64F
* Remove command line dump from the docs
* Ignore bad unicode characters
* Allow colorama versions 0.4.x
* Check decoded output for test errors
=> Release version 1.5.0

src/htrun/host_tests_runner/target_base.py
Access the 'create' via importing from `mbed_ls_tools` instead of detect
=> Update Create call in target_base python

src/htrun/__init__.py, src/htrun/host_tests_plugins/module_copy_pyocd.py
Forward port from https://github.com/ARMmbed/mbed-os-tools/pull/263
=> Allow to pass the file format to pyocd

setup.py, src/htrun/host_tests_plugins/module_copy_pyocd.py, src/htrun/host_tests_runner/target_base.py
=> Update pyOCD to v0.31.0

setup.py
Port of https://github.com/ARMmbed/mbed-os-tools/pull/274 to `greentea` standalone repo
=> Update pyOCD to v0.32.0
